name: Build & Push Frontend to Azure ACR

on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - 'public/**'
      - 'Dockerfile'
      - 'package.json'
      - 'package-lock.json'
      - 'nginx.conf'
  
  workflow_dispatch: 

env:
  IMAGE_NAME: frontend  

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    environment: dev   

    steps:
      # 1. Checkout del repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Login en Azure ACR 
      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ vars.REGISTRY }}   
          username: ${{ secrets.AZURE_ACR_USERNAME }}
          password: ${{ secrets.AZURE_ACR_PASSWORD }}

      # 3. Configurar versión semántica automática
      - name: Bump version
        id: version
        uses: phips28/gh-action-bump-version@v10
        with:
          tag-prefix: ""   
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # 4. Construir imagen Docker
      - name: Build Docker image
        run: |
          docker build -t ${{ vars.REGISTRY }}/$IMAGE_NAME:${{ steps.version.outputs.newTag }} .
          docker tag ${{ vars.REGISTRY }}/$IMAGE_NAME:${{ steps.version.outputs.newTag }} ${{ vars.REGISTRY }}/$IMAGE_NAME:latest

      # 5. Subir la imagen a ACR
      - name: Push Docker image
        run: |
          docker push ${{ vars.REGISTRY }}/$IMAGE_NAME:${{ steps.version.outputs.newTag }}
          docker push ${{ vars.REGISTRY }}/$IMAGE_NAME:latest
