name: Build & Push Frontend to Azure ACR

on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - 'public/**'
      - 'Dockerfile'
      - 'package.json'
      - 'package-lock.json'
      - 'nginx.conf'
  
  workflow_dispatch: 

permissions:
  contents: write  

env:
  IMAGE_NAME: frontend  

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    environment: dev   

    steps:
      # 1. Checkout del repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Login en Azure ACR 
      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ vars.REGISTRY }}   
          username: ${{ secrets.AZURE_ACR_USERNAME }}
          password: ${{ secrets.AZURE_ACR_PASSWORD }}

      # 3. Configurar versión semántica automática
      - name: Bump version
        id: version
        uses: phips28/gh-action-bump-version@v11.0.7
        with:
          tag-prefix: ""   
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # 🔎 Debug variables críticas
      - name: Debug Docker variables
        run: |
          echo "REGISTRY raw value between brackets: [${{ vars.REGISTRY }}]"
          echo "REGISTRY with cat -A (muestra caracteres ocultos):"
          echo "${{ vars.REGISTRY }}" | cat -A
          echo "IMAGE_NAME: [${{ env.IMAGE_NAME }}]"
          echo "TAG: [${{ steps.version.outputs.newTag }}]"

      # 🔎 Verificar archivos del contexto Docker
      - name: Check context files
        run: |
          ls -la
          if [ -f Dockerfile ]; then echo "Dockerfile found"; else echo "Dockerfile missing!"; fi

      # 4. Construir imagen Docker (limpiando \r)
      - name: Build Docker image
        run: |
          set -x
          # Limpiar caracteres CR (\r) en REGISTRY
          REGISTRY_CLEAN=$(echo "${{ vars.REGISTRY }}" | tr -d '\r')
          echo "Using cleaned REGISTRY: [$REGISTRY_CLEAN]"
          docker build -t $REGISTRY_CLEAN/${{ env.IMAGE_NAME }}:${{ steps.version.outputs.newTag }} .
          docker tag $REGISTRY_CLEAN/${{ env.IMAGE_NAME }}:${{ steps.version.outputs.newTag }} $REGISTRY_CLEAN/${{ env.IMAGE_NAME }}:latest

      # 5. Subir la imagen a ACR
      - name: Push Docker image
        run: |
          REGISTRY_CLEAN=$(echo "${{ vars.REGISTRY }}" | tr -d '\r')
          docker push $REGISTRY_CLEAN/${{ env.IMAGE_NAME }}:${{ steps.version.outputs.newTag }}
          docker push $REGISTRY_CLEAN/${{ env.IMAGE_NAME }}:latest
